"""Add ProgressUpdate model for audit trail

Revision ID: d6c4330ff3eb
Revises: df83ab219d9d
Create Date: 2025-10-05 14:17:15.320409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c4330ff3eb'
down_revision = 'df83ab219d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_value', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('proof_url', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_update', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_update_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_league'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_league'), ['league'], unique=False)

    with op.batch_alter_table('progress_update', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_update_timestamp'))

    op.drop_table('progress_update')
    # ### end Alembic commands ###
