"""Add weight column to Goal model

Revision ID: dcf1367fd5e6
Revises: d6a51cc16bf9
Create Date: 2025-10-04 19:25:45.154043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf1367fd5e6'
down_revision = 'd6a51cc16bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=False, server_default='5'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
